# Generated by Django 3.1 on 2021-09-24 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0002_auto_20210924_1626'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ('date_created',)},
        ),
        migrations.RemoveField(
            model_name='voteanswer',
            name='sign',
        ),
        migrations.RemoveField(
            model_name='votequestion',
            name='sign',
        ),
        migrations.AddField(
            model_name='voteanswer',
            name='value',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='votequestion',
            name='value',
            field=models.SmallIntegerField(default=0),
        ),
    ]
