# Generated by Django 3.1 on 2021-09-24 22:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qa', '0003_auto_20210924_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='votes',
            field=models.ManyToManyField(related_name='answer_votes', through='qa.VoteAnswer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='votes',
            field=models.ManyToManyField(related_name='question_votes', through='qa.VoteQuestion', to=settings.AUTH_USER_MODEL),
        ),
    ]
