# Generated by Django 3.1 on 2021-09-25 08:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qa', '0005_auto_20210925_0137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voteanswer',
            old_name='answer',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='votequestion',
            old_name='question',
            new_name='post',
        ),
        migrations.AlterUniqueTogether(
            name='voteanswer',
            unique_together={('author', 'post')},
        ),
        migrations.AlterUniqueTogether(
            name='votequestion',
            unique_together={('author', 'post')},
        ),
    ]
