# Generated by Django 3.1 on 2021-10-08 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0006_auto_20210925_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='header',
            field=models.CharField(max_length=500, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='questions', to='qa.Tag'),
        ),
    ]
